name: tyme
description: Tyme Mobile
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^12.1.1
  lottie: ^2.3.2
  provider: ^6.0.5
  flutter_markdown: ^0.6.18+2
  mqtt5_client: ^4.0.3
  flutter_native_splash: ^2.3.5
  collection: ^1.18.0
  flutter_local_notifications: ^16.1.0
  flutter_timezone: ^1.0.4
  timezone: ^0.9.0
  rxdart: ^0.27.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  file_picker: ^6.1.1
  nanoid: ^1.0.0
  mime_type: ^1.0.0
  crypto: ^3.0.3
  visibility_detector: ^0.4.0+2
  flutter_displaymode: ^0.6.0
  easy_refresh: ^3.3.3+1
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/lottie/
    - assets/image/

flutter_native_splash:
  color: "#42a5f5"
  android_12:

